### PR TITLE
use latest stable node for travis tests

### PR DESCRIPTION
**Pull request by ngoldman**

### CODE REVIEW

**Comment by Flet** [comment]
Interesting, no legacy node checks now?

**Comment by ngoldman** [comment]
@Flet I think that can be left up to the author. Stable seems like a good default to me. Do you think it's worth adding another option for the author to decide which nodes to target?

**Comment by bcomnes** [comment]
Maybe default to latest and LTS?

**Comment by Flet** [comment]
Tweet from seldo a few days ago:

Major(ish) node versions, requests in last 7 days:
0.12  779 MM
0.10  732 MM
4   222 MM
2   22 MM
3   19 MM
1   6 MM

**Comment by ngoldman** [comment]
Definitely a wide range. With that said, I don't think we want to be covering 6 versions for every travis test by default, right? It would make sense to test for 0.10, 0.12, and 4, but I feel like that's already a lot too. @Flet @bcomnes suggestions welcome.

**Comment by bcomnes** [comment]
I think a small set of sensible defaults works for me, and ideologically, I believe people should be targeting at least stable.  

Until module-init has a re-init function for updating boilerplate, I would probably just let people manually add in older versions, its literally one line in a yaml file.

**Comment by Flet** [comment]
Just looking at numbers:

`4.x` (stable) would cover **12.47%** of current node clients
`4.x` + `0.12` would cover **56.24%** of current node clients
`4.x` + `0.12` + `0.10` would cover **97.36%** of current node clients

What's great about travis is its fairly async and does not really cost more to cover additional engines (other than time to run). For public packages, covering `4.x` + `0.12` + `0.10` seems the most prudent to me .

A lot of people seemed to hold back from upgrading to `0.12`, so `0.10` still has quite a big audience... 

hah, @bcomnes commented above just popped in.

**Comment by ngoldman** [comment]
Thanks for the feedback! My spidey sense is telling me there's one vote for just stable and one vote for stable, 0.12, and 0.10. Is that right?

**Comment by ngoldman** [comment]
Another option would be to detect what version of node the user is running and just default to that.

**Comment by ngoldman** [comment]
(That's easily doable with process.version)

**Comment by ngoldman** [comment]
ping @flet @bcomnes ^ :wave:

**Comment by Flet** [comment]
whats the downside of testing many versions? Just speed?

**Comment by ngoldman** [comment]
Speed and relevance to new projects. I'm also inclined not to throw in the kitchen sink unless there's a good reason to.

**Comment by Flet** [comment]
In an ideal world, all programs that depend on a package would be using the latest stable version of node. For various reasons, some programs/users are still running on older versions of node. This could be due to neglect or due to other logistical reasons. 

The numbers above show that users are split across the last three versions of node (with most users either one or two versions behind `stable` currently).

If I'm building a new package, I want to ensure most users will not run into issues when depending on it. I want to test in environments that cover a good portion of what actual user's are using. Right now `stable`only covers about 12% of users. If the cost of also covering additional users is a couple more minutes of travis time, I'm OK with that.

At the very least, I'd be happy to have `stable` and `stable - 1` as default targets. 

I wish travis had a way of specifying `stable -1` though, as it would avoid the need to manually bump things every node release... :cry:

**Comment by ngoldman** [comment]
Okay you've made some good points. I'll go ahead and put 0.12 back in.

**Pull request merged**
