### PR TITLE
add linter to questions

### PR DESCRIPTION
**Pull request by Flet**
lint

Pick linter (default `standard`)

### CODE REVIEW

**Comment by ngoldman** [comment]
@Flet lgtm but I merged your other PR first, can you rebase?

**Comment by Flet** [comment]
:+1:

**Comment by ngoldman** [comment]
@Flet moved `pkgLinter` from `required` to `defaults` (standard is default). Released in [0.3.1](https://github.com/ngoldman/module-init/releases/tag/v0.3.1). Thanks for the contrib!

:tada:

**Comment by Flet** [comment]
Ah cool, I missed `defaults` :)

**Pull request merged**
