### PR TITLE
Added TAP summarizer option.

### PR DESCRIPTION
**Pull request by bcomnes**
Faucet is great, but suffers from some compatibility issues on windows.  Seems fair to offer some TAP summarizer options.  I promise I'm not trying to turn this into yeoman

### CODE REVIEW

**Comment by Flet** [comment]
I concur with @bcomnes: `faucet` explodes on Windows when run on its own.

This does work in Windows though: `tape test/*.js | faucet`

The problem is when `faucet` tries to spawn `tape` (good ol' #2318 in joyent/node). So this gets around it by piping instead.

**Comment by ngoldman** [comment]
If that's the case I think we might as well just plain switch to tap-spec. The only reason I was using faucet instead was because it was less to write (`standard && faucet` vs `standard && tape test/*.js | tap-spec`). I don't think we need to overload the initialization options with something tape output formatting.

**Comment by Flet** [comment]
`faucet` output looks pretty janky on Windows anyways. `tap-spec` looks nice though.

**Comment by Flet** [comment]
I don't get the expected/actual output using `tap-spec` on tests. Maybe that's a personal problem though.

**Comment by ngoldman** [comment]
@Flet what do you mean by expected/actual? can you elaborate? I don't think I get what you say you don't get

**Comment by Flet** [comment]
### faucet:
image

### tap-spec:
image

### plain old tape:
image

**Comment by Flet** [comment]
ah, scottcorgan/tap-spec#29

**Comment by Flet** [comment]
Heh, `npm install -g tap-spec@2.2.2` looks a lot better to me! :)
image

From the issue above, looks like they are trying to work it out.

**Comment by ngoldman** [comment]
closing this in favor of defaulting to tap-spec unless there's a strong case for needing more than one tap output prettifier

**Pull request closed without merging**
